name: "Task / Bug / Documentation"
description: "Single template for any type of issue"
title: "[Area] Short description"
labels: ["pending"]
body:
  - type: textarea
    id: description
    attributes:
      label: 📝 Description
      description: "Describe what needs to be done or what bug needs to be fixed."
      placeholder: "Example: Configure GitHub Actions to deploy the backend on AWS."
  - type: textarea
    id: steps
    attributes:
      label: ✅ Steps / Checklist
      description: "List subtasks or steps to complete this issue."
      placeholder: |
        - [ ] Step 1
        - [ ] Step 2
  - type: textarea
    id: done
    attributes:
      label: 📌 Definition of Done
      description: "When this task is considered completed."
      placeholder: |
        - Code tested locally
        - Tests pass in CI/CD
        - Documentation updated
  - type: textarea
    id: dependencies
    attributes:
      label: 🔗 Dependencies
      description: "Mention if this task depends on another issue or PR."
      placeholder: "Example: depends on #12 for the database to be ready."
  - type: textarea
    id: notes
    attributes:
      label: 💡 Additional Notes
      description: "Extra context, screenshots or links."
